name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'  # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Use Secret
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAPAPIKEY }}
        run: |
          echo "The API key is $OPENWEATHERMAP_API_KEY"  
        
