name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'  # Specify the .NET version
      
      - name: Install Xamarin
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind8 gettext
          wget https://dl.xamarin.com/android/ndk/android-ndk-r21d-linux-x86_64.zip
          unzip android-ndk-r21d-linux-x86_64.zip
          export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21d
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Use Secret
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAPAPIKEY }}
        run: |
          echo "The API key is $OPENWEATHERMAP_API_KEY"  
        
